language: node_js
dist: trusty
sudo: required
node_js:
  - 'node'

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/prod/
  github_token: $GITHUB_TOKEN
  on:
    branch: master